;;; This file was automatically generated by SWIG (http://www.swig.org).
;;; Version 2.0.8
;;;
;;; Do not make changes to this file unless you know what you are doing--modify
;;; the SWIG interface file instead.


;;;SWIG wrapper code starts here

(cl:defmacro defanonenum (&body enums)
   "Converts anonymous enums to defconstants."
  `(cl:progn ,@(cl:loop for value in enums
                        for index = 0 then (cl:1+ index)
                        when (cl:listp value) do (cl:setf index (cl:second value)
                                                          value (cl:first value))
                        collect `(cl:defconstant ,value ,index))))

(cl:eval-when (:compile-toplevel :load-toplevel)
  (cl:unless (cl:fboundp 'swig-lispify)
    (cl:defun swig-lispify (name flag cl:&optional (package cl:*package*))
      (cl:labels ((helper (lst last rest cl:&aux (c (cl:car lst)))
                    (cl:cond
                      ((cl:null lst)
                       rest)
                      ((cl:upper-case-p c)
                       (helper (cl:cdr lst) 'upper
                               (cl:case last
                                 ((lower digit) (cl:list* c #\- rest))
                                 (cl:t (cl:cons c rest)))))
                      ((cl:lower-case-p c)
                       (helper (cl:cdr lst) 'lower (cl:cons (cl:char-upcase c) rest)))
                      ((cl:digit-char-p c)
                       (helper (cl:cdr lst) 'digit 
                               (cl:case last
                                 ((upper lower) (cl:list* c #\- rest))
                                 (cl:t (cl:cons c rest)))))
                      ((cl:char-equal c #\_)
                       (helper (cl:cdr lst) '_ (cl:cons #\- rest)))
                      (cl:t
                       (cl:error "Invalid character: ~A" c)))))
        (cl:let ((fix (cl:case flag
                        ((constant enumvalue) "+")
                        (variable "*")
                        (cl:t ""))))
          (cl:intern
           (cl:concatenate
            'cl:string
            fix
            (cl:nreverse (helper (cl:concatenate 'cl:list name) cl:nil cl:nil))
            fix)
           package))))))

;;;SWIG wrapper code ends here


(cl:defconstant FL_CAPS_LOCK #x00020000)

(cl:defconstant FL_MAJOR_VERSION 1)

(cl:defconstant FL_MINOR_VERSION 3)

(cl:defconstant FL_PATCH_VERSION 0)

(cffi:defcenum Fl_Event
	(:FL_NO_EVENT #.0)
	(:FL_PUSH #.1)
	(:FL_RELEASE #.2)
	(:FL_ENTER #.3)
	(:FL_LEAVE #.4)
	(:FL_DRAG #.5)
	(:FL_FOCUS #.6)
	(:FL_UNFOCUS #.7)
	(:FL_KEYDOWN #.8)
	(:FL_KEYBOARD #.8)
	(:FL_KEYUP #.9)
	(:FL_CLOSE #.10)
	(:FL_MOVE #.11)
	(:FL_SHORTCUT #.12)
	(:FL_DEACTIVATE #.13)
	(:FL_ACTIVATE #.14)
	(:FL_HIDE #.15)
	(:FL_SHOW #.16)
	(:FL_PASTE #.17)
	(:FL_SELECTIONCLEAR #.18)
	(:FL_MOUSEWHEEL #.19)
	(:FL_DND_ENTER #.20)
	(:FL_DND_DRAG #.21)
	(:FL_DND_LEAVE #.22)
	(:FL_DND_RELEASE #.23)
	(:FL_SCREEN_CONFIGURATION_CHANGED #.24)
	(:FL_FULLSCREEN #.25))

(cffi:defcenum Fl_When
	(:FL_WHEN_NEVER #.0)
	(:FL_WHEN_CHANGED #.1)
	(:FL_WHEN_NOT_CHANGED #.2)
	(:FL_WHEN_RELEASE #.4)
	(:FL_WHEN_RELEASE_ALWAYS #.6)
	(:FL_WHEN_ENTER_KEY #.8)
	(:FL_WHEN_ENTER_KEY_ALWAYS #.10)
	(:FL_WHEN_ENTER_KEY_CHANGED #.11))

(cl:defconstant FL_Button #xfee8)

(cl:defconstant FL_BackSpace #xff08)

(cl:defconstant FL_Tab #xff09)

(cl:defconstant FL_Iso_Key #xff0c)

(cl:defconstant FL_Enter #xff0d)

(cl:defconstant FL_Pause #xff13)

(cl:defconstant FL_Scroll_Lock #xff14)

(cl:defconstant FL_Escape #xff1b)

(cl:defconstant FL_Home #xff50)

(cl:defconstant FL_Left #xff51)

(cl:defconstant FL_Up #xff52)

(cl:defconstant FL_Right #xff53)

(cl:defconstant FL_Down #xff54)

(cl:defconstant FL_Page_Up #xff55)

(cl:defconstant FL_Page_Down #xff56)

(cl:defconstant FL_End #xff57)

(cl:defconstant FL_Print #xff61)

(cl:defconstant FL_Insert #xff63)

(cl:defconstant FL_Menu #xff67)

(cl:defconstant FL_Help #xff68)

(cl:defconstant FL_Num_Lock #xff7f)

(cl:defconstant FL_KP #xff80)

(cl:defconstant FL_KP_Enter #xff8d)

(cl:defconstant FL_KP_Last #xffbd)

(cl:defconstant FL_F #xffbd)

(cl:defconstant FL_F_Last #xffe0)

(cl:defconstant FL_Shift_L #xffe1)

(cl:defconstant FL_Shift_R #xffe2)

(cl:defconstant FL_Control_L #xffe3)

(cl:defconstant FL_Control_R #xffe4)

(cl:defconstant FL_Caps_Lock #xffe5)

(cl:defconstant FL_Meta_L #xffe7)

(cl:defconstant FL_Meta_R #xffe8)

(cl:defconstant FL_Alt_L #xffe9)

(cl:defconstant FL_Alt_R #xffea)

(cl:defconstant FL_Delete #xffff)

(cl:defconstant FL_Volume_Down #xEF11)

(cl:defconstant FL_Volume_Mute #xEF12)

(cl:defconstant FL_Volume_Up #xEF13)

(cl:defconstant FL_Media_Play #xEF14)

(cl:defconstant FL_Media_Stop #xEF15)

(cl:defconstant FL_Media_Prev #xEF16)

(cl:defconstant FL_Media_Next #xEF17)

(cl:defconstant FL_Home_Page #xEF18)

(cl:defconstant FL_Mail #xEF19)

(cl:defconstant FL_Search #xEF1B)

(cl:defconstant FL_Back #xEF26)

(cl:defconstant FL_Forward #xEF27)

(cl:defconstant FL_Stop #xEF28)

(cl:defconstant FL_Refresh #xEF29)

(cl:defconstant FL_Sleep #xEF2F)

(cl:defconstant FL_Favorites #xEF30)

(cl:defconstant FL_LEFT_MOUSE 1)

(cl:defconstant FL_MIDDLE_MOUSE 2)

(cl:defconstant FL_RIGHT_MOUSE 3)

(cl:defconstant FL_SHIFT #x00010000)

(cl:defconstant FL_CTRL #x00040000)

(cl:defconstant FL_ALT #x00080000)

(cl:defconstant FL_NUM_LOCK #x00100000)

(cl:defconstant FL_META #x00400000)

(cl:defconstant FL_SCROLL_LOCK #x00800000)

(cl:defconstant FL_BUTTON1 #x01000000)

(cl:defconstant FL_BUTTON2 #x02000000)

(cl:defconstant FL_BUTTON3 #x04000000)

(cl:defconstant FL_BUTTONS #x7f000000)

(cl:defconstant FL_KEY_MASK #x0000ffff)

(cl:defconstant FL_COMMAND #x00040000)

(cl:defconstant FL_CONTROL #x00400000)

(cffi:defcenum Fl_Boxtype
	(:FL_NO_BOX #.0)
	:FL_FLAT_BOX
	:FL_UP_BOX
	:FL_DOWN_BOX
	:FL_UP_FRAME
	:FL_DOWN_FRAME
	:FL_THIN_UP_BOX
	:FL_THIN_DOWN_BOX
	:FL_THIN_UP_FRAME
	:FL_THIN_DOWN_FRAME
	:FL_ENGRAVED_BOX
	:FL_EMBOSSED_BOX
	:FL_ENGRAVED_FRAME
	:FL_EMBOSSED_FRAME
	:FL_BORDER_BOX
	:_FL_SHADOW_BOX
	:FL_BORDER_FRAME
	:_FL_SHADOW_FRAME
	:_FL_ROUNDED_BOX
	:_FL_RSHADOW_BOX
	:_FL_ROUNDED_FRAME
	:_FL_RFLAT_BOX
	:_FL_ROUND_UP_BOX
	:_FL_ROUND_DOWN_BOX
	:_FL_DIAMOND_UP_BOX
	:_FL_DIAMOND_DOWN_BOX
	:_FL_OVAL_BOX
	:_FL_OSHADOW_BOX
	:_FL_OVAL_FRAME
	:_FL_OFLAT_BOX
	:_FL_PLASTIC_UP_BOX
	:_FL_PLASTIC_DOWN_BOX
	:_FL_PLASTIC_UP_FRAME
	:_FL_PLASTIC_DOWN_FRAME
	:_FL_PLASTIC_THIN_UP_BOX
	:_FL_PLASTIC_THIN_DOWN_BOX
	:_FL_PLASTIC_ROUND_UP_BOX
	:_FL_PLASTIC_ROUND_DOWN_BOX
	:_FL_GTK_UP_BOX
	:_FL_GTK_DOWN_BOX
	:_FL_GTK_UP_FRAME
	:_FL_GTK_DOWN_FRAME
	:_FL_GTK_THIN_UP_BOX
	:_FL_GTK_THIN_DOWN_BOX
	:_FL_GTK_THIN_UP_FRAME
	:_FL_GTK_THIN_DOWN_FRAME
	:_FL_GTK_ROUND_UP_BOX
	:_FL_GTK_ROUND_DOWN_BOX
	:FL_FREE_BOXTYPE)

(cffi:defcfun ("_wrap_fl_define_FL_ROUND_UP_BOX" fl_define_FL_ROUND_UP_BOX) Fl_Boxtype)

(cffi:defcfun ("_wrap_fl_define_FL_SHADOW_BOX" fl_define_FL_SHADOW_BOX) Fl_Boxtype)

(cffi:defcfun ("_wrap_fl_define_FL_ROUNDED_BOX" fl_define_FL_ROUNDED_BOX) Fl_Boxtype)

(cffi:defcfun ("_wrap_fl_define_FL_RFLAT_BOX" fl_define_FL_RFLAT_BOX) Fl_Boxtype)

(cffi:defcfun ("_wrap_fl_define_FL_RSHADOW_BOX" fl_define_FL_RSHADOW_BOX) Fl_Boxtype)

(cffi:defcfun ("_wrap_fl_define_FL_DIAMOND_BOX" fl_define_FL_DIAMOND_BOX) Fl_Boxtype)

(cffi:defcfun ("_wrap_fl_define_FL_OVAL_BOX" fl_define_FL_OVAL_BOX) Fl_Boxtype)

(cffi:defcfun ("_wrap_fl_define_FL_PLASTIC_UP_BOX" fl_define_FL_PLASTIC_UP_BOX) Fl_Boxtype)

(cffi:defcfun ("_wrap_fl_define_FL_GTK_UP_BOX" fl_define_FL_GTK_UP_BOX) Fl_Boxtype)

(cffi:defcfun ("_wrap_fl_box" fl_box) Fl_Boxtype
  (b Fl_Boxtype))

(cffi:defcfun ("_wrap_fl_down" fl_down) Fl_Boxtype
  (b Fl_Boxtype))

(cffi:defcfun ("_wrap_fl_frame" fl_frame) Fl_Boxtype
  (b Fl_Boxtype))

(cffi:defcenum Fl_Labeltype
	(:FL_NORMAL_LABEL #.0)
	:FL_NO_LABEL
	:_FL_SHADOW_LABEL
	:_FL_ENGRAVED_LABEL
	:_FL_EMBOSSED_LABEL
	:_FL_MULTI_LABEL
	:_FL_ICON_LABEL
	:_FL_IMAGE_LABEL
	:FL_FREE_LABELTYPE)

(cffi:defcfun ("_wrap_fl_define_FL_SHADOW_LABEL" fl_define_FL_SHADOW_LABEL) Fl_Labeltype)

(cffi:defcfun ("_wrap_fl_define_FL_ENGRAVED_LABEL" fl_define_FL_ENGRAVED_LABEL) Fl_Labeltype)

(cffi:defcfun ("_wrap_fl_define_FL_EMBOSSED_LABEL" fl_define_FL_EMBOSSED_LABEL) Fl_Labeltype)

(cl:defconstant FL_NUM_FREE_COLOR 16)

(cl:defconstant FL_NUM_GRAY 24)

(cl:defconstant FL_NUM_RED 5)

(cl:defconstant FL_NUM_GREEN 8)

(cl:defconstant FL_NUM_BLUE 5)

(cffi:defcfun ("_wrap_fl_inactive" fl_inactive) :unsigned-int
  (c :unsigned-int))

(cffi:defcfun ("_wrap_fl_contrast" fl_contrast) :unsigned-int
  (fg :unsigned-int)
  (bg :unsigned-int))

(cffi:defcfun ("_wrap_fl_color_average" fl_color_average) :unsigned-int
  (c1 :unsigned-int)
  (c2 :unsigned-int)
  (weight :float))

(cffi:defcfun ("_wrap_fl_lighter" fl_lighter) :unsigned-int
  (c :unsigned-int))

(cffi:defcfun ("_wrap_fl_darker" fl_darker) :unsigned-int
  (c :unsigned-int))

(cffi:defcfun ("_wrap_fl_rgb_color__SWIG_0" fl_rgb_color) :unsigned-int
  (r :unsigned-char)
  (g :unsigned-char)
  (b :unsigned-char))

(cffi:defcfun ("_wrap_fl_rgb_color__SWIG_1" fl_rgb_color) :unsigned-int
  (g :unsigned-char))

(cffi:defcfun ("_wrap_fl_gray_ramp" fl_gray_ramp) :unsigned-int
  (i :int))

(cffi:defcfun ("_wrap_fl_color_cube" fl_color_cube) :unsigned-int
  (r :int)
  (g :int)
  (b :int))

(cffi:defcenum Fl_Cursor
	(:FL_CURSOR_DEFAULT #.0)
	(:FL_CURSOR_ARROW #.1)
	(:FL_CURSOR_CROSS #.2)
	(:FL_CURSOR_WAIT #.3)
	(:FL_CURSOR_INSERT #.4)
	(:FL_CURSOR_HAND #.5)
	(:FL_CURSOR_HELP #.6)
	(:FL_CURSOR_MOVE #.7)
	(:FL_CURSOR_NS #.101)
	(:FL_CURSOR_WE #.102)
	(:FL_CURSOR_NWSE #.103)
	(:FL_CURSOR_NESW #.104)
	(:FL_CURSOR_NE #.110)
	(:FL_CURSOR_N #.111)
	(:FL_CURSOR_NW #.112)
	(:FL_CURSOR_E #.113)
	(:FL_CURSOR_W #.114)
	(:FL_CURSOR_SE #.115)
	(:FL_CURSOR_S #.116)
	(:FL_CURSOR_SW #.117)
	(:FL_CURSOR_NONE #.255))

(defanonenum 
	(FL_READ #.1)
	(FL_WRITE #.4)
	(FL_EXCEPT #.8))

(cffi:defcenum Fl_Mode
	(:FL_RGB #.0)
	(:FL_INDEX #.1)
	(:FL_SINGLE #.0)
	(:FL_DOUBLE #.2)
	(:FL_ACCUM #.4)
	(:FL_ALPHA #.8)
	(:FL_DEPTH #.16)
	(:FL_STENCIL #.32)
	(:FL_RGB8 #.64)
	(:FL_MULTISAMPLE #.128)
	(:FL_STEREO #.256)
	(:FL_FAKE_SINGLE #.512))

(cl:defconstant FL_IMAGE_WITH_ALPHA #x40000000)

(cffi:defcenum Fl_Damage
	(:FL_DAMAGE_CHILD #.#x01)
	(:FL_DAMAGE_EXPOSE #.#x02)
	(:FL_DAMAGE_SCROLL #.#x04)
	(:FL_DAMAGE_OVERLAY #.#x08)
	(:FL_DAMAGE_USER1 #.#x10)
	(:FL_DAMAGE_USER2 #.#x20)
	(:FL_DAMAGE_ALL #.#x80))

(cffi:defcfun ("_wrap_Fl_call_screen_init" Fl_call_screen_init) :void)

(cffi:defcfun ("_wrap_Fl_damage__SWIG_0" Fl_damage) :void
  (d :int))

(cffi:defcenum Fl_Option
	(:OPTION_ARROW_FOCUS #.0)
	:OPTION_VISIBLE_FOCUS
	:OPTION_DND_TEXT
	:OPTION_SHOW_TOOLTIPS
	:OPTION_LAST)

(cffi:defcfun ("_wrap_Fl_option__SWIG_0" Fl_option) :pointer
  (opt :pointer))

(cffi:defcfun ("_wrap_Fl_option__SWIG_1" Fl_option) :void
  (opt :pointer)
  (val :pointer))

(cffi:defcfun ("_wrap_Fl_add_awake_handler_" Fl_add_awake_handler_) :int
  (arg0 :pointer)
  (arg1 :pointer))

(cffi:defcfun ("_wrap_Fl_version" Fl_version) :double)

(cffi:defcfun ("_wrap_Fl_arg" Fl_arg) :int
  (argc :int)
  (argv :pointer)
  (i :pointer))

(cffi:defcfun ("_wrap_Fl_args__SWIG_0" Fl_args) :int
  (argc :int)
  (argv :pointer)
  (i :pointer)
  (cb :pointer))

(cffi:defcfun ("_wrap_Fl_args__SWIG_1" Fl_args) :void
  (argc :int)
  (argv :pointer))

(cffi:defcfun ("_wrap_Fl_display" Fl_display) :void
  (arg0 :string))

(cffi:defcfun ("_wrap_Fl_visual" Fl_visual) :int
  (arg0 :int))

(cffi:defcfun ("_wrap_Fl_own_colormap" Fl_own_colormap) :void)

(cffi:defcfun ("_wrap_Fl_get_system_colors" Fl_get_system_colors) :void)

(cffi:defcfun ("_wrap_Fl_foreground" Fl_foreground) :void
  (arg0 :unsigned-char)
  (arg1 :unsigned-char)
  (arg2 :unsigned-char))

(cffi:defcfun ("_wrap_Fl_background" Fl_background) :void
  (arg0 :unsigned-char)
  (arg1 :unsigned-char)
  (arg2 :unsigned-char))

(cffi:defcfun ("_wrap_Fl_background2" Fl_background2) :void
  (arg0 :unsigned-char)
  (arg1 :unsigned-char)
  (arg2 :unsigned-char))

(cffi:defcfun ("_wrap_Fl_scheme__SWIG_0" Fl_scheme) :int
  (arg0 :string))

(cffi:defcfun ("_wrap_Fl_scheme__SWIG_1" Fl_scheme) :string)

(cffi:defcfun ("_wrap_Fl_reload_scheme" Fl_reload_scheme) :int)

(cffi:defcfun ("_wrap_Fl_scrollbar_size__SWIG_0" Fl_scrollbar_size) :int)

(cffi:defcfun ("_wrap_Fl_scrollbar_size__SWIG_1" Fl_scrollbar_size) :void
  (W :int))

(cffi:defcfun ("_wrap_Fl_wait__SWIG_0" Fl_wait) :int)

(cffi:defcfun ("_wrap_Fl_wait__SWIG_1" Fl_wait) :double
  (time :double))

(cffi:defcfun ("_wrap_Fl_check" Fl_check) :int)

(cffi:defcfun ("_wrap_Fl_ready" Fl_ready) :int)

(cffi:defcfun ("_wrap_Fl_run" Fl_run) :int)

(cffi:defcfun ("_wrap_Fl_readqueue" Fl_readqueue) :pointer)

(cffi:defcfun ("_wrap_Fl_has_timeout" Fl_has_timeout) :int
  (arg0 :pointer)
  (arg1 :pointer))

(cffi:defcfun ("_wrap_Fl_add_idle" Fl_add_idle) :void
  (cb :pointer)
  (data :pointer))

(cffi:defcfun ("_wrap_Fl_has_idle" Fl_has_idle) :int
  (cb :pointer)
  (data :pointer))

(cffi:defcfun ("_wrap_Fl_remove_idle" Fl_remove_idle) :void
  (cb :pointer)
  (data :pointer))

(cffi:defcfun ("_wrap_Fl_damage__SWIG_1" Fl_damage) :int)

(cffi:defcfun ("_wrap_Fl_redraw" Fl_redraw) :void)

(cffi:defcfun ("_wrap_Fl_flush" Fl_flush) :void)

(cffi:defcfun ("_wrap_Fl_first_window__SWIG_0" Fl_first_window) :pointer)

(cffi:defcfun ("_wrap_Fl_first_window__SWIG_1" Fl_first_window) :void
  (arg0 :pointer))

(cffi:defcfun ("_wrap_Fl_next_window" Fl_next_window) :pointer
  (arg0 :pointer))

(cffi:defcfun ("_wrap_Fl_modal" Fl_modal) :pointer)

(cffi:defcfun ("_wrap_Fl_grab__SWIG_0" Fl_grab) :pointer)

(cffi:defcfun ("_wrap_Fl_grab__SWIG_1" Fl_grab) :void
  (arg0 :pointer))

(cffi:defcfun ("_wrap_Fl_event" Fl_event) :int)

(cffi:defcfun ("_wrap_Fl_event_x" Fl_event_x) :int)

(cffi:defcfun ("_wrap_Fl_event_y" Fl_event_y) :int)

(cffi:defcfun ("_wrap_Fl_event_x_root" Fl_event_x_root) :int)

(cffi:defcfun ("_wrap_Fl_event_y_root" Fl_event_y_root) :int)

(cffi:defcfun ("_wrap_Fl_event_dx" Fl_event_dx) :int)

(cffi:defcfun ("_wrap_Fl_event_dy" Fl_event_dy) :int)

(cffi:defcfun ("_wrap_Fl_get_mouse" Fl_get_mouse) :void
  (arg0 :pointer)
  (arg1 :pointer))

(cffi:defcfun ("_wrap_Fl_event_clicks__SWIG_0" Fl_event_clicks) :int)

(cffi:defcfun ("_wrap_Fl_event_clicks__SWIG_1" Fl_event_clicks) :void
  (i :int))

(cffi:defcfun ("_wrap_Fl_event_is_click__SWIG_0" Fl_event_is_click) :int)

(cffi:defcfun ("_wrap_Fl_event_is_click__SWIG_1" Fl_event_is_click) :void
  (i :int))

(cffi:defcfun ("_wrap_Fl_event_button" Fl_event_button) :int)

(cffi:defcfun ("_wrap_Fl_event_state__SWIG_0" Fl_event_state) :int)

(cffi:defcfun ("_wrap_Fl_event_state__SWIG_1" Fl_event_state) :int
  (i :int))

(cffi:defcfun ("_wrap_Fl_event_key__SWIG_0" Fl_event_key) :int)

(cffi:defcfun ("_wrap_Fl_event_original_key" Fl_event_original_key) :int)

(cffi:defcfun ("_wrap_Fl_event_key__SWIG_1" Fl_event_key) :int
  (key :int))

(cffi:defcfun ("_wrap_Fl_get_key" Fl_get_key) :int
  (key :int))

(cffi:defcfun ("_wrap_Fl_event_text" Fl_event_text) :string)

(cffi:defcfun ("_wrap_Fl_event_length" Fl_event_length) :int)

(cffi:defcfun ("_wrap_Fl_compose" Fl_compose) :int
  (del :pointer))

(cffi:defcfun ("_wrap_Fl_compose_reset" Fl_compose_reset) :void)

(cffi:defcfun ("_wrap_Fl_event_inside__SWIG_0" Fl_event_inside) :int
  (arg0 :int)
  (arg1 :int)
  (arg2 :int)
  (arg3 :int))

(cffi:defcfun ("_wrap_Fl_event_inside__SWIG_1" Fl_event_inside) :int
  (arg0 :pointer))

(cffi:defcfun ("_wrap_Fl_test_shortcut" Fl_test_shortcut) :int
  (arg0 :pointer))

(cffi:defcfun ("_wrap_Fl_handle" Fl_handle) :int
  (arg0 :int)
  (arg1 :pointer))

(cffi:defcfun ("_wrap_Fl_handle_" Fl_handle_) :int
  (arg0 :int)
  (arg1 :pointer))

(cffi:defcfun ("_wrap_Fl_belowmouse__SWIG_0" Fl_belowmouse) :pointer)

(cffi:defcfun ("_wrap_Fl_belowmouse__SWIG_1" Fl_belowmouse) :void
  (arg0 :pointer))

(cffi:defcfun ("_wrap_Fl_pushed__SWIG_0" Fl_pushed) :pointer)

(cffi:defcfun ("_wrap_Fl_pushed__SWIG_1" Fl_pushed) :void
  (arg0 :pointer))

(cffi:defcfun ("_wrap_Fl_focus__SWIG_0" Fl_focus) :pointer)

(cffi:defcfun ("_wrap_Fl_focus__SWIG_1" Fl_focus) :void
  (arg0 :pointer))

(cffi:defcfun ("_wrap_Fl_event_dispatch__SWIG_0" Fl_event_dispatch) :void
  (d :pointer))

(cffi:defcfun ("_wrap_Fl_event_dispatch__SWIG_1" Fl_event_dispatch) :pointer)

(cffi:defcfun ("_wrap_Fl_copy" Fl_copy) :void
  (stuff :string)
  (len :int)
  (destination :int))

(cffi:defcfun ("_wrap_Fl_paste__SWIG_0" Fl_paste) :void
  (receiver :pointer)
  (source :int))

(cffi:defcfun ("_wrap_Fl_add_clipboard_notify" Fl_add_clipboard_notify) :void
  (h :pointer)
  (data :pointer))

(cffi:defcfun ("_wrap_Fl_remove_clipboard_notify" Fl_remove_clipboard_notify) :void
  (h :pointer))

(cffi:defcfun ("_wrap_Fl_dnd" Fl_dnd) :int)

(cffi:defcfun ("_wrap_Fl_selection_owner__SWIG_0" Fl_selection_owner) :pointer)

(cffi:defcfun ("_wrap_Fl_selection_owner__SWIG_1" Fl_selection_owner) :void
  (arg0 :pointer))

(cffi:defcfun ("_wrap_Fl_selection" Fl_selection) :void
  (owner :pointer)
  (arg1 :string)
  (len :int))

(cffi:defcfun ("_wrap_Fl_paste__SWIG_1" Fl_paste) :void
  (receiver :pointer))

(cffi:defcfun ("_wrap_Fl_x" Fl_x) :int)

(cffi:defcfun ("_wrap_Fl_y" Fl_y) :int)

(cffi:defcfun ("_wrap_Fl_w" Fl_w) :int)

(cffi:defcfun ("_wrap_Fl_h" Fl_h) :int)

(cffi:defcfun ("_wrap_Fl_screen_count" Fl_screen_count) :int)

(cffi:defcfun ("_wrap_Fl_screen_xywh__SWIG_0" Fl_screen_xywh) :void
  (X :pointer)
  (Y :pointer)
  (W :pointer)
  (H :pointer))

(cffi:defcfun ("_wrap_Fl_screen_xywh__SWIG_1" Fl_screen_xywh) :void
  (X :pointer)
  (Y :pointer)
  (W :pointer)
  (H :pointer)
  (mx :int)
  (my :int))

(cffi:defcfun ("_wrap_Fl_screen_xywh__SWIG_2" Fl_screen_xywh) :void
  (X :pointer)
  (Y :pointer)
  (W :pointer)
  (H :pointer)
  (n :int))

(cffi:defcfun ("_wrap_Fl_screen_xywh__SWIG_3" Fl_screen_xywh) :void
  (X :pointer)
  (Y :pointer)
  (W :pointer)
  (H :pointer)
  (mx :int)
  (my :int)
  (mw :int)
  (mh :int))

(cffi:defcfun ("_wrap_Fl_screen_num__SWIG_0" Fl_screen_num) :int
  (x :int)
  (y :int))

(cffi:defcfun ("_wrap_Fl_screen_num__SWIG_1" Fl_screen_num) :int
  (x :int)
  (y :int)
  (w :int)
  (h :int))

(cffi:defcfun ("_wrap_Fl_screen_dpi" Fl_screen_dpi) :void
  (h :pointer)
  (v :pointer)
  (n :int))

(cffi:defcfun ("_wrap_Fl_screen_work_area__SWIG_0" Fl_screen_work_area) :void
  (X :pointer)
  (Y :pointer)
  (W :pointer)
  (H :pointer)
  (mx :int)
  (my :int))

(cffi:defcfun ("_wrap_Fl_screen_work_area__SWIG_1" Fl_screen_work_area) :void
  (X :pointer)
  (Y :pointer)
  (W :pointer)
  (H :pointer)
  (n :int))

(cffi:defcfun ("_wrap_Fl_screen_work_area__SWIG_2" Fl_screen_work_area) :void
  (X :pointer)
  (Y :pointer)
  (W :pointer)
  (H :pointer))

(cffi:defcfun ("_wrap_Fl_set_color__SWIG_0" Fl_set_color) :void
  (arg0 :unsigned-int)
  (arg1 :unsigned-char)
  (arg2 :unsigned-char)
  (arg3 :unsigned-char))

(cffi:defcfun ("_wrap_Fl_set_color__SWIG_1" Fl_set_color) :void
  (i :unsigned-int)
  (c :unsigned-int))

(cffi:defcfun ("_wrap_Fl_get_color" Fl_get_color) :void
  (i :unsigned-int)
  (red :pointer)
  (green :pointer)
  (blue :pointer))

(cffi:defcfun ("_wrap_Fl_free_color" Fl_free_color) :void
  (i :unsigned-int)
  (overlay :int))

(cffi:defcfun ("_wrap_Fl_get_font" Fl_get_font) :string
  (arg0 :int))

(cffi:defcfun ("_wrap_Fl_get_font_name" Fl_get_font_name) :string
  (arg0 :int)
  (attributes :pointer))

(cffi:defcfun ("_wrap_Fl_get_font_sizes" Fl_get_font_sizes) :int
  (arg0 :int)
  (sizep :pointer))

(cffi:defcfun ("_wrap_Fl_set_font__SWIG_0" Fl_set_font) :void
  (arg0 :int)
  (arg1 :string))

(cffi:defcfun ("_wrap_Fl_set_font__SWIG_1" Fl_set_font) :void
  (arg0 :int)
  (arg1 :int))

(cffi:defcfun ("_wrap_Fl_set_fonts" Fl_set_fonts) :int
  (arg0 :string))

(cffi:defcfun ("_wrap_Fl_set_labeltype" Fl_set_labeltype) :void
  (arg0 Fl_Labeltype)
  (arg1 :pointer)
  (arg2 :pointer))

(cffi:defcfun ("_wrap_Fl_get_boxtype" Fl_get_boxtype) :pointer
  (arg0 Fl_Boxtype))

(cffi:defcfun ("_wrap_Fl_set_boxtype__SWIG_0" Fl_set_boxtype) :void
  (arg0 Fl_Boxtype)
  (arg1 :pointer)
  (arg2 :unsigned-char)
  (arg3 :unsigned-char)
  (arg4 :unsigned-char)
  (arg5 :unsigned-char))

(cffi:defcfun ("_wrap_Fl_set_boxtype__SWIG_1" Fl_set_boxtype) :void
  (arg0 Fl_Boxtype)
  (from Fl_Boxtype))

(cffi:defcfun ("_wrap_Fl_box_dx" Fl_box_dx) :int
  (arg0 Fl_Boxtype))

(cffi:defcfun ("_wrap_Fl_box_dy" Fl_box_dy) :int
  (arg0 Fl_Boxtype))

(cffi:defcfun ("_wrap_Fl_box_dw" Fl_box_dw) :int
  (arg0 Fl_Boxtype))

(cffi:defcfun ("_wrap_Fl_box_dh" Fl_box_dh) :int
  (arg0 Fl_Boxtype))

(cffi:defcfun ("_wrap_Fl_draw_box_active" Fl_draw_box_active) :int)

(cffi:defcfun ("_wrap_Fl_set_abort" Fl_set_abort) :void
  (f :pointer))

(cffi:defcfun ("_wrap_Fl_default_atclose" Fl_default_atclose) :void
  (arg0 :pointer)
  (arg1 :pointer))

(cffi:defcfun ("_wrap_Fl_set_atclose" Fl_set_atclose) :void
  (f :pointer))

(cffi:defcfun ("_wrap_Fl_event_shift" Fl_event_shift) :int)

(cffi:defcfun ("_wrap_Fl_event_ctrl" Fl_event_ctrl) :int)

(cffi:defcfun ("_wrap_Fl_event_command" Fl_event_command) :int)

(cffi:defcfun ("_wrap_Fl_event_alt" Fl_event_alt) :int)

(cffi:defcfun ("_wrap_Fl_event_buttons" Fl_event_buttons) :int)

(cffi:defcfun ("_wrap_Fl_event_button1" Fl_event_button1) :int)

(cffi:defcfun ("_wrap_Fl_event_button2" Fl_event_button2) :int)

(cffi:defcfun ("_wrap_Fl_event_button3" Fl_event_button3) :int)

(cffi:defcfun ("_wrap_Fl_set_idle" Fl_set_idle) :void
  (cb :pointer))

(cffi:defcfun ("_wrap_Fl_release" Fl_release) :void)

(cffi:defcfun ("_wrap_Fl_visible_focus__SWIG_0" Fl_visible_focus) :void
  (v :int))

(cffi:defcfun ("_wrap_Fl_visible_focus__SWIG_1" Fl_visible_focus) :int)

(cffi:defcfun ("_wrap_Fl_dnd_text_ops__SWIG_0" Fl_dnd_text_ops) :void
  (v :int))

(cffi:defcfun ("_wrap_Fl_dnd_text_ops__SWIG_1" Fl_dnd_text_ops) :int)

(cffi:defcfun ("_wrap_Fl_lock" Fl_lock) :int)

(cffi:defcfun ("_wrap_Fl_unlock" Fl_unlock) :void)

(cffi:defcfun ("_wrap_Fl_awake__SWIG_0" Fl_awake) :void
  (message :pointer))

(cffi:defcfun ("_wrap_Fl_awake__SWIG_1" Fl_awake) :int
  (cb :pointer)
  (message :pointer))

(cffi:defcfun ("_wrap_Fl_thread_message" Fl_thread_message) :pointer)

(cffi:defcfun ("_wrap_Fl_delete_widget" Fl_delete_widget) :void
  (w :pointer))

(cffi:defcfun ("_wrap_Fl_do_widget_deletion" Fl_do_widget_deletion) :void)

(cffi:defcfun ("_wrap_Fl_watch_widget_pointer" Fl_watch_widget_pointer) :void
  (w :pointer))

(cffi:defcfun ("_wrap_Fl_release_widget_pointer" Fl_release_widget_pointer) :void
  (w :pointer))

(cffi:defcfun ("_wrap_Fl_clear_widget_pointer" Fl_clear_widget_pointer) :void
  (w :pointer))

(cffi:defcfun ("_wrap_delete_Fl" delete_Fl) :void
  (self :pointer))

(cffi:defcfun ("_wrap_new_Fl_Widget_Tracker" new_Fl_Widget_Tracker) :pointer
  (wi :pointer))

(cffi:defcfun ("_wrap_delete_Fl_Widget_Tracker" delete_Fl_Widget_Tracker) :void
  (self :pointer))

(cffi:defcfun ("_wrap_Fl_Widget_Tracker_widget" Fl_Widget_Tracker_widget) :pointer
  (self :pointer))

(cffi:defcfun ("_wrap_Fl_Widget_Tracker_deleted" Fl_Widget_Tracker_deleted) :int
  (self :pointer))

(cffi:defcfun ("_wrap_Fl_Widget_Tracker_exists" Fl_Widget_Tracker_exists) :int
  (self :pointer))

(defanonenum 
	(INACTIVE #.(cl:ash 1 0))
	(INVISIBLE #.(cl:ash 1 1))
	(OUTPUT #.(cl:ash 1 2))
	(NOBORDER #.(cl:ash 1 3))
	(FORCE_POSITION #.(cl:ash 1 4))
	(NON_MODAL #.(cl:ash 1 5))
	(SHORTCUT_LABEL #.(cl:ash 1 6))
	(CHANGED #.(cl:ash 1 7))
	(OVERRIDE #.(cl:ash 1 8))
	(VISIBLE_FOCUS #.(cl:ash 1 9))
	(COPIED_LABEL #.(cl:ash 1 10))
	(CLIP_CHILDREN #.(cl:ash 1 11))
	(MENU_WINDOW #.(cl:ash 1 12))
	(TOOLTIP_WINDOW #.(cl:ash 1 13))
	(MODAL #.(cl:ash 1 14))
	(NO_OVERLAY #.(cl:ash 1 15))
	(GROUP_RELATIVE #.(cl:ash 1 16))
	(COPIED_TOOLTIP #.(cl:ash 1 17))
	(FULLSCREEN #.(cl:ash 1 18))
	(SIMPLE_KEYBOARD #.(cl:ash 1 19))
	(USERFLAG3 #.(cl:ash 1 29))
	(USERFLAG2 #.(cl:ash 1 30))
	(USERFLAG1 #.(cl:ash 1 31)))

(cffi:defcfun ("_wrap_delete_Fl_Widget" delete_Fl_Widget) :void
  (self :pointer))

(cffi:defcfun ("_wrap_Fl_Widget_draw" Fl_Widget_draw) :void
  (self :pointer))

(cffi:defcfun ("_wrap_Fl_Widget_handle" Fl_Widget_handle) :int
  (self :pointer)
  (event :int))

(cffi:defcfun ("_wrap_Fl_Widget_parent__SWIG_0" Fl_Widget_parent) :pointer
  (self :pointer))

(cffi:defcfun ("_wrap_Fl_Widget_parent__SWIG_1" Fl_Widget_parent) :void
  (self :pointer)
  (p :pointer))

(cffi:defcfun ("_wrap_Fl_Widget_type__SWIG_0" Fl_Widget_type) :unsigned-char
  (self :pointer))

(cffi:defcfun ("_wrap_Fl_Widget_type__SWIG_1" Fl_Widget_type) :void
  (self :pointer)
  (t_arg1 :unsigned-char))

(cffi:defcfun ("_wrap_Fl_Widget_x" Fl_Widget_x) :int
  (self :pointer))

(cffi:defcfun ("_wrap_Fl_Widget_y" Fl_Widget_y) :int
  (self :pointer))

(cffi:defcfun ("_wrap_Fl_Widget_w" Fl_Widget_w) :int
  (self :pointer))

(cffi:defcfun ("_wrap_Fl_Widget_h" Fl_Widget_h) :int
  (self :pointer))

(cffi:defcfun ("_wrap_Fl_Widget_resize" Fl_Widget_resize) :void
  (self :pointer)
  (x :int)
  (y :int)
  (w :int)
  (h :int))

(cffi:defcfun ("_wrap_Fl_Widget_damage_resize" Fl_Widget_damage_resize) :int
  (self :pointer)
  (arg1 :int)
  (arg2 :int)
  (arg3 :int)
  (arg4 :int))

(cffi:defcfun ("_wrap_Fl_Widget_position" Fl_Widget_position) :void
  (self :pointer)
  (X :int)
  (Y :int))

(cffi:defcfun ("_wrap_Fl_Widget_size" Fl_Widget_size) :void
  (self :pointer)
  (W :int)
  (H :int))

(cffi:defcfun ("_wrap_Fl_Widget_align__SWIG_0" Fl_Widget_align) :unsigned-int
  (self :pointer))

(cffi:defcfun ("_wrap_Fl_Widget_align__SWIG_1" Fl_Widget_align) :void
  (self :pointer)
  (alignment :unsigned-int))

(cffi:defcfun ("_wrap_Fl_Widget_box__SWIG_0" Fl_Widget_box) Fl_Boxtype
  (self :pointer))

(cffi:defcfun ("_wrap_Fl_Widget_box__SWIG_1" Fl_Widget_box) :void
  (self :pointer)
  (new_box Fl_Boxtype))

(cffi:defcfun ("_wrap_Fl_Widget_color__SWIG_0" Fl_Widget_color) :unsigned-int
  (self :pointer))

(cffi:defcfun ("_wrap_Fl_Widget_color__SWIG_1" Fl_Widget_color) :void
  (self :pointer)
  (bg :unsigned-int))

(cffi:defcfun ("_wrap_Fl_Widget_selection_color__SWIG_0" Fl_Widget_selection_color) :unsigned-int
  (self :pointer))

(cffi:defcfun ("_wrap_Fl_Widget_selection_color__SWIG_1" Fl_Widget_selection_color) :void
  (self :pointer)
  (a :unsigned-int))

(cffi:defcfun ("_wrap_Fl_Widget_color__SWIG_2" Fl_Widget_color) :void
  (self :pointer)
  (bg :unsigned-int)
  (sel :unsigned-int))

(cffi:defcfun ("_wrap_Fl_Widget_label__SWIG_0" Fl_Widget_label) :string
  (self :pointer))

(cffi:defcfun ("_wrap_Fl_Widget_label__SWIG_1" Fl_Widget_label) :void
  (self :pointer)
  (text :string))

(cffi:defcfun ("_wrap_Fl_Widget_copy_label" Fl_Widget_copy_label) :void
  (self :pointer)
  (new_label :string))

(cffi:defcfun ("_wrap_Fl_Widget_label__SWIG_2" Fl_Widget_label) :void
  (self :pointer)
  (a Fl_Labeltype)
  (b :string))

(cffi:defcfun ("_wrap_Fl_Widget_labeltype__SWIG_0" Fl_Widget_labeltype) Fl_Labeltype
  (self :pointer))

(cffi:defcfun ("_wrap_Fl_Widget_labeltype__SWIG_1" Fl_Widget_labeltype) :void
  (self :pointer)
  (a Fl_Labeltype))

(cffi:defcfun ("_wrap_Fl_Widget_labelcolor__SWIG_0" Fl_Widget_labelcolor) :unsigned-int
  (self :pointer))

(cffi:defcfun ("_wrap_Fl_Widget_labelcolor__SWIG_1" Fl_Widget_labelcolor) :void
  (self :pointer)
  (c :unsigned-int))

(cffi:defcfun ("_wrap_Fl_Widget_labelfont__SWIG_0" Fl_Widget_labelfont) :int
  (self :pointer))

(cffi:defcfun ("_wrap_Fl_Widget_labelfont__SWIG_1" Fl_Widget_labelfont) :void
  (self :pointer)
  (f :int))

(cffi:defcfun ("_wrap_Fl_Widget_labelsize__SWIG_0" Fl_Widget_labelsize) :int
  (self :pointer))

(cffi:defcfun ("_wrap_Fl_Widget_labelsize__SWIG_1" Fl_Widget_labelsize) :void
  (self :pointer)
  (pix :int))

(cffi:defcfun ("_wrap_Fl_Widget_image__SWIG_0" Fl_Widget_image) :pointer
  (self :pointer))

(cffi:defcfun ("_wrap_Fl_Widget_image__SWIG_1" Fl_Widget_image) :pointer
  (self :pointer))

(cffi:defcfun ("_wrap_Fl_Widget_image__SWIG_2" Fl_Widget_image) :void
  (self :pointer)
  (img :pointer))

(cffi:defcfun ("_wrap_Fl_Widget_deimage__SWIG_0" Fl_Widget_deimage) :pointer
  (self :pointer))

(cffi:defcfun ("_wrap_Fl_Widget_deimage__SWIG_1" Fl_Widget_deimage) :pointer
  (self :pointer))

(cffi:defcfun ("_wrap_Fl_Widget_deimage__SWIG_2" Fl_Widget_deimage) :void
  (self :pointer)
  (img :pointer))

(cffi:defcfun ("_wrap_Fl_Widget_tooltip__SWIG_0" Fl_Widget_tooltip) :string
  (self :pointer))

(cffi:defcfun ("_wrap_Fl_Widget_tooltip__SWIG_1" Fl_Widget_tooltip) :void
  (self :pointer)
  (text :string))

(cffi:defcfun ("_wrap_Fl_Widget_copy_tooltip" Fl_Widget_copy_tooltip) :void
  (self :pointer)
  (text :string))

(cffi:defcfun ("_wrap_Fl_Widget_callback__SWIG_0" Fl_Widget_callback) :pointer
  (self :pointer))

(cffi:defcfun ("_wrap_Fl_Widget_callback__SWIG_1" Fl_Widget_callback) :void
  (self :pointer)
  (cb :pointer)
  (p :pointer))

(cffi:defcfun ("_wrap_Fl_Widget_callback__SWIG_2" Fl_Widget_callback) :void
  (self :pointer)
  (cb :pointer))

(cffi:defcfun ("_wrap_Fl_Widget_callback__SWIG_3" Fl_Widget_callback) :void
  (self :pointer)
  (cb :pointer))

(cffi:defcfun ("_wrap_Fl_Widget_callback__SWIG_4" Fl_Widget_callback) :void
  (self :pointer)
  (cb :pointer)
  (p :long))

(cffi:defcfun ("_wrap_Fl_Widget_user_data__SWIG_0" Fl_Widget_user_data) :pointer
  (self :pointer))

(cffi:defcfun ("_wrap_Fl_Widget_user_data__SWIG_1" Fl_Widget_user_data) :void
  (self :pointer)
  (v :pointer))

(cffi:defcfun ("_wrap_Fl_Widget_argument__SWIG_0" Fl_Widget_argument) :long
  (self :pointer))

(cffi:defcfun ("_wrap_Fl_Widget_argument__SWIG_1" Fl_Widget_argument) :void
  (self :pointer)
  (v :long))

(cffi:defcfun ("_wrap_Fl_Widget_when__SWIG_0" Fl_Widget_when) Fl_When
  (self :pointer))

(cffi:defcfun ("_wrap_Fl_Widget_when__SWIG_1" Fl_Widget_when) :void
  (self :pointer)
  (i :unsigned-char))

(cffi:defcfun ("_wrap_Fl_Widget_visible" Fl_Widget_visible) :unsigned-int
  (self :pointer))

(cffi:defcfun ("_wrap_Fl_Widget_visible_r" Fl_Widget_visible_r) :int
  (self :pointer))

(cffi:defcfun ("_wrap_Fl_Widget_show" Fl_Widget_show) :void
  (self :pointer))

(cffi:defcfun ("_wrap_Fl_Widget_hide" Fl_Widget_hide) :void
  (self :pointer))

(cffi:defcfun ("_wrap_Fl_Widget_set_visible" Fl_Widget_set_visible) :void
  (self :pointer))

(cffi:defcfun ("_wrap_Fl_Widget_clear_visible" Fl_Widget_clear_visible) :void
  (self :pointer))

(cffi:defcfun ("_wrap_Fl_Widget_active" Fl_Widget_active) :unsigned-int
  (self :pointer))

(cffi:defcfun ("_wrap_Fl_Widget_active_r" Fl_Widget_active_r) :int
  (self :pointer))

(cffi:defcfun ("_wrap_Fl_Widget_activate" Fl_Widget_activate) :void
  (self :pointer))

(cffi:defcfun ("_wrap_Fl_Widget_deactivate" Fl_Widget_deactivate) :void
  (self :pointer))

(cffi:defcfun ("_wrap_Fl_Widget_output" Fl_Widget_output) :unsigned-int
  (self :pointer))

(cffi:defcfun ("_wrap_Fl_Widget_set_output" Fl_Widget_set_output) :void
  (self :pointer))

(cffi:defcfun ("_wrap_Fl_Widget_clear_output" Fl_Widget_clear_output) :void
  (self :pointer))

(cffi:defcfun ("_wrap_Fl_Widget_takesevents" Fl_Widget_takesevents) :unsigned-int
  (self :pointer))

(cffi:defcfun ("_wrap_Fl_Widget_changed" Fl_Widget_changed) :unsigned-int
  (self :pointer))

(cffi:defcfun ("_wrap_Fl_Widget_set_changed" Fl_Widget_set_changed) :void
  (self :pointer))

(cffi:defcfun ("_wrap_Fl_Widget_clear_changed" Fl_Widget_clear_changed) :void
  (self :pointer))

(cffi:defcfun ("_wrap_Fl_Widget_simple_keyboard" Fl_Widget_simple_keyboard) :unsigned-int
  (self :pointer))

(cffi:defcfun ("_wrap_Fl_Widget_set_simple_keyboard" Fl_Widget_set_simple_keyboard) :void
  (self :pointer))

(cffi:defcfun ("_wrap_Fl_Widget_set_normal_keyboard" Fl_Widget_set_normal_keyboard) :void
  (self :pointer))

(cffi:defcfun ("_wrap_Fl_Widget_take_focus" Fl_Widget_take_focus) :int
  (self :pointer))

(cffi:defcfun ("_wrap_Fl_Widget_set_visible_focus" Fl_Widget_set_visible_focus) :void
  (self :pointer))

(cffi:defcfun ("_wrap_Fl_Widget_clear_visible_focus" Fl_Widget_clear_visible_focus) :void
  (self :pointer))

(cffi:defcfun ("_wrap_Fl_Widget_visible_focus__SWIG_0" Fl_Widget_visible_focus) :void
  (self :pointer)
  (v :int))

(cffi:defcfun ("_wrap_Fl_Widget_visible_focus__SWIG_1" Fl_Widget_visible_focus) :unsigned-int
  (self :pointer))

(cffi:defcfun ("_wrap_Fl_Widget_default_callback" Fl_Widget_default_callback) :void
  (cb :pointer)
  (d :pointer))

(cffi:defcfun ("_wrap_Fl_Widget_do_callback__SWIG_0" Fl_Widget_do_callback) :void
  (self :pointer))

(cffi:defcfun ("_wrap_Fl_Widget_do_callback__SWIG_1" Fl_Widget_do_callback) :void
  (self :pointer)
  (o :pointer)
  (arg :long))

(cffi:defcfun ("_wrap_Fl_Widget_do_callback__SWIG_2" Fl_Widget_do_callback) :void
  (self :pointer)
  (o :pointer)
  (arg :pointer))

(cffi:defcfun ("_wrap_Fl_Widget_test_shortcut__SWIG_0" Fl_Widget_test_shortcut) :int
  (self :pointer))

(cffi:defcfun ("_wrap_Fl_Widget_label_shortcut" Fl_Widget_label_shortcut) :unsigned-int
  (t_arg0 :string))

(cffi:defcfun ("_wrap_Fl_Widget_test_shortcut__SWIG_1" Fl_Widget_test_shortcut) :int
  (arg0 :string)
  (require_alt :pointer))

(cffi:defcfun ("_wrap_Fl_Widget__set_fullscreen" Fl_Widget__set_fullscreen) :void
  (self :pointer))

(cffi:defcfun ("_wrap_Fl_Widget__clear_fullscreen" Fl_Widget__clear_fullscreen) :void
  (self :pointer))

(cffi:defcfun ("_wrap_Fl_Widget_contains" Fl_Widget_contains) :int
  (self :pointer)
  (w :pointer))

(cffi:defcfun ("_wrap_Fl_Widget_inside" Fl_Widget_inside) :int
  (self :pointer)
  (wgt :pointer))

(cffi:defcfun ("_wrap_Fl_Widget_redraw" Fl_Widget_redraw) :void
  (self :pointer))

(cffi:defcfun ("_wrap_Fl_Widget_redraw_label" Fl_Widget_redraw_label) :void
  (self :pointer))

(cffi:defcfun ("_wrap_Fl_Widget_damage__SWIG_0" Fl_Widget_damage) :unsigned-char
  (self :pointer))

(cffi:defcfun ("_wrap_Fl_Widget_clear_damage" Fl_Widget_clear_damage) :void
  (self :pointer)
  (c :unsigned-char))

(cffi:defcfun ("_wrap_Fl_Widget_damage__SWIG_1" Fl_Widget_damage) :void
  (self :pointer)
  (c :unsigned-char))

(cffi:defcfun ("_wrap_Fl_Widget_damage__SWIG_2" Fl_Widget_damage) :void
  (self :pointer)
  (c :unsigned-char)
  (x :int)
  (y :int)
  (w :int)
  (h :int))

(cffi:defcfun ("_wrap_Fl_Widget_draw_label" Fl_Widget_draw_label) :void
  (self :pointer)
  (arg1 :int)
  (arg2 :int)
  (arg3 :int)
  (arg4 :int)
  (arg5 :unsigned-int))

(cffi:defcfun ("_wrap_Fl_Widget_measure_label" Fl_Widget_measure_label) :void
  (self :pointer)
  (ww :pointer)
  (hh :pointer))

(cffi:defcfun ("_wrap_Fl_Widget_window" Fl_Widget_window) :pointer
  (self :pointer))

(cffi:defcfun ("_wrap_Fl_Widget_as_group" Fl_Widget_as_group) :pointer
  (self :pointer))

(cffi:defcfun ("_wrap_Fl_Widget_as_window" Fl_Widget_as_window) :pointer
  (self :pointer))

(cffi:defcfun ("_wrap_Fl_Widget_as_gl_window" Fl_Widget_as_gl_window) :pointer
  (self :pointer))

(cffi:defcfun ("_wrap_Fl_Widget_color2__SWIG_0" Fl_Widget_color2) :unsigned-int
  (self :pointer))

(cffi:defcfun ("_wrap_Fl_Widget_color2__SWIG_1" Fl_Widget_color2) :void
  (self :pointer)
  (a :unsigned-int))

(cl:defconstant FL_RESERVED_TYPE 100)

(cffi:defcfun ("_wrap_Fl_Group_handle" Fl_Group_handle) :int
  (self :pointer)
  (arg1 :int))

(cffi:defcfun ("_wrap_Fl_Group_begin" Fl_Group_begin) :void
  (self :pointer))

(cffi:defcfun ("_wrap_Fl_Group_end" Fl_Group_end) :void
  (self :pointer))

(cffi:defcfun ("_wrap_Fl_Group_current__SWIG_0" Fl_Group_current) :pointer)

(cffi:defcfun ("_wrap_Fl_Group_current__SWIG_1" Fl_Group_current) :void
  (g :pointer))

(cffi:defcfun ("_wrap_Fl_Group_children" Fl_Group_children) :int
  (self :pointer))

(cffi:defcfun ("_wrap_Fl_Group_child" Fl_Group_child) :pointer
  (self :pointer)
  (n :int))

(cffi:defcfun ("_wrap_Fl_Group_find" Fl_Group_find) :int
  (self :pointer)
  (o :pointer))

(cffi:defcfun ("_wrap_Fl_Group_resize" Fl_Group_resize) :void
  (self :pointer)
  (arg1 :int)
  (arg2 :int)
  (arg3 :int)
  (arg4 :int))

(cffi:defcfun ("_wrap_new_Fl_Group" new_Fl_Group) :pointer
  (arg0 :int)
  (arg1 :int)
  (arg2 :int)
  (arg3 :int)
  (arg4 :string))

(cffi:defcfun ("_wrap_delete_Fl_Group" delete_Fl_Group) :void
  (self :pointer))

(cffi:defcfun ("_wrap_Fl_Group_add" Fl_Group_add) :void
  (self :pointer)
  (o :pointer))

(cffi:defcfun ("_wrap_Fl_Group_insert" Fl_Group_insert) :void
  (self :pointer)
  (arg1 :pointer)
  (i :int))

(cffi:defcfun ("_wrap_Fl_Group_insert_before" Fl_Group_insert_before) :void
  (self :pointer)
  (o :pointer)
  (before :pointer))

(cffi:defcfun ("_wrap_Fl_Group_remove__SWIG_0" Fl_Group_remove) :void
  (self :pointer)
  (index :int))

(cffi:defcfun ("_wrap_Fl_Group_remove__SWIG_1" Fl_Group_remove) :void
  (self :pointer)
  (o :pointer))

(cffi:defcfun ("_wrap_Fl_Group_clear" Fl_Group_clear) :void
  (self :pointer))

(cffi:defcfun ("_wrap_Fl_Group_resizable__SWIG_0" Fl_Group_resizable) :void
  (self :pointer)
  (o :pointer))

(cffi:defcfun ("_wrap_Fl_Group_resizable__SWIG_1" Fl_Group_resizable) :pointer
  (self :pointer))

(cffi:defcfun ("_wrap_Fl_Group_add_resizable" Fl_Group_add_resizable) :void
  (self :pointer)
  (o :pointer))

(cffi:defcfun ("_wrap_Fl_Group_init_sizes" Fl_Group_init_sizes) :void
  (self :pointer))

(cffi:defcfun ("_wrap_Fl_Group_clip_children__SWIG_0" Fl_Group_clip_children) :void
  (self :pointer)
  (c :int))

(cffi:defcfun ("_wrap_Fl_Group_clip_children__SWIG_1" Fl_Group_clip_children) :unsigned-int
  (self :pointer))

(cffi:defcfun ("_wrap_Fl_Group_as_group" Fl_Group_as_group) :pointer
  (self :pointer))

(cffi:defcfun ("_wrap_Fl_Group_focus" Fl_Group_focus) :void
  (self :pointer)
  (W :pointer))

(cffi:defcfun ("_wrap_Fl_Group__ddfdesign_kludge" Fl_Group__ddfdesign_kludge) :pointer
  (self :pointer))

(cffi:defcfun ("_wrap_Fl_Group_forms_end" Fl_Group_forms_end) :void
  (self :pointer))

(cffi:defcfun ("_wrap_new_Fl_End" new_Fl_End) :pointer)

(cffi:defcfun ("_wrap_delete_Fl_End" delete_Fl_End) :void
  (self :pointer))

(cl:defconstant FL_WINDOW #xF0)

(cl:defconstant FL_DOUBLE_WINDOW #xF1)

(cffi:defcfun ("_wrap_new_Fl_Window_3" new_Fl_Window_3) :pointer
  (w :int)
  (h :int)
  (title :string))

(cffi:defcfun ("_wrap_new_Fl_Window_5" new_Fl_Window_5) :pointer
  (x :int)
  (y :int)
  (w :int)
  (h :int)
  (title :string))

(cffi:defcfun ("_wrap_delete_Fl_Window" delete_Fl_Window) :void
  (self :pointer))

(cffi:defcfun ("_wrap_Fl_Window_handle" Fl_Window_handle) :int
  (self :pointer)
  (arg1 :int))

(cffi:defcfun ("_wrap_Fl_Window_resize" Fl_Window_resize) :void
  (self :pointer)
  (X :int)
  (Y :int)
  (W :int)
  (H :int))

(cffi:defcfun ("_wrap_Fl_Window_border__SWIG_0" Fl_Window_border) :void
  (self :pointer)
  (b :int))

(cffi:defcfun ("_wrap_Fl_Window_clear_border" Fl_Window_clear_border) :void
  (self :pointer))

(cffi:defcfun ("_wrap_Fl_Window_border__SWIG_1" Fl_Window_border) :unsigned-int
  (self :pointer))

(cffi:defcfun ("_wrap_Fl_Window_set_override" Fl_Window_set_override) :void
  (self :pointer))

(cffi:defcfun ("_wrap_Fl_Window_override" Fl_Window_override) :unsigned-int
  (self :pointer))

(cffi:defcfun ("_wrap_Fl_Window_set_modal" Fl_Window_set_modal) :void
  (self :pointer))

(cffi:defcfun ("_wrap_Fl_Window_modal" Fl_Window_modal) :unsigned-int
  (self :pointer))

(cffi:defcfun ("_wrap_Fl_Window_set_non_modal" Fl_Window_set_non_modal) :void
  (self :pointer))

(cffi:defcfun ("_wrap_Fl_Window_non_modal" Fl_Window_non_modal) :unsigned-int
  (self :pointer))

(cffi:defcfun ("_wrap_Fl_Window_set_menu_window" Fl_Window_set_menu_window) :void
  (self :pointer))

(cffi:defcfun ("_wrap_Fl_Window_menu_window" Fl_Window_menu_window) :unsigned-int
  (self :pointer))

(cffi:defcfun ("_wrap_Fl_Window_set_tooltip_window" Fl_Window_set_tooltip_window) :void
  (self :pointer))

(cffi:defcfun ("_wrap_Fl_Window_tooltip_window" Fl_Window_tooltip_window) :unsigned-int
  (self :pointer))

(cffi:defcfun ("_wrap_Fl_Window_hotspot__SWIG_0" Fl_Window_hotspot) :void
  (self :pointer)
  (x :int)
  (y :int)
  (offscreen :int))

(cffi:defcfun ("_wrap_Fl_Window_hotspot__SWIG_1" Fl_Window_hotspot) :void
  (self :pointer)
  (arg1 :pointer)
  (offscreen :int))

(cffi:defcfun ("_wrap_Fl_Window_free_position" Fl_Window_free_position) :void
  (self :pointer))

(cffi:defcfun ("_wrap_Fl_Window_size_range" Fl_Window_size_range) :void
  (self :pointer)
  (minw :int)
  (minh :int)
  (maxw :int)
  (maxh :int)
  (dw :int)
  (dh :int)
  (aspect :int))

(cffi:defcfun ("_wrap_Fl_Window_label__SWIG_0" Fl_Window_label) :string
  (self :pointer))

(cffi:defcfun ("_wrap_Fl_Window_iconlabel__SWIG_0" Fl_Window_iconlabel) :string
  (self :pointer))

(cffi:defcfun ("_wrap_Fl_Window_label__SWIG_1" Fl_Window_label) :void
  (self :pointer)
  (arg1 :string))

(cffi:defcfun ("_wrap_Fl_Window_iconlabel__SWIG_1" Fl_Window_iconlabel) :void
  (self :pointer)
  (arg1 :string))

(cffi:defcfun ("_wrap_Fl_Window_label__SWIG_2" Fl_Window_label) :void
  (self :pointer)
  (label :string)
  (iconlabel :string))

(cffi:defcfun ("_wrap_Fl_Window_copy_label" Fl_Window_copy_label) :void
  (self :pointer)
  (a :string))

(cffi:defcfun ("_wrap_Fl_Window_default_xclass__SWIG_0" Fl_Window_default_xclass) :void
  (arg0 :string))

(cffi:defcfun ("_wrap_Fl_Window_default_xclass__SWIG_1" Fl_Window_default_xclass) :string)

(cffi:defcfun ("_wrap_Fl_Window_xclass__SWIG_0" Fl_Window_xclass) :string
  (self :pointer))

(cffi:defcfun ("_wrap_Fl_Window_xclass__SWIG_1" Fl_Window_xclass) :void
  (self :pointer)
  (c :string))

(cffi:defcfun ("_wrap_Fl_Window_default_icon" Fl_Window_default_icon) :void
  (arg0 :pointer))

(cffi:defcfun ("_wrap_Fl_Window_default_icons" Fl_Window_default_icons) :void
  (arg0 :pointer)
  (arg1 :int))

(cffi:defcfun ("_wrap_Fl_Window_icon__SWIG_0" Fl_Window_icon) :void
  (self :pointer)
  (arg1 :pointer))

(cffi:defcfun ("_wrap_Fl_Window_icons" Fl_Window_icons) :void
  (self :pointer)
  (arg1 :pointer)
  (arg2 :int))

(cffi:defcfun ("_wrap_Fl_Window_icon__SWIG_1" Fl_Window_icon) :pointer
  (self :pointer))

(cffi:defcfun ("_wrap_Fl_Window_icon__SWIG_2" Fl_Window_icon) :void
  (self :pointer)
  (ic :pointer))

(cffi:defcfun ("_wrap_Fl_Window_shown" Fl_Window_shown) :int
  (self :pointer))

(cffi:defcfun ("_wrap_Fl_Window_show" Fl_Window_show) :void
  (self :pointer))

(cffi:defcfun ("_wrap_Fl_Window_hide" Fl_Window_hide) :void
  (self :pointer))

(cffi:defcfun ("_wrap_Fl_Window_fullscreen" Fl_Window_fullscreen) :void
  (self :pointer))

(cffi:defcfun ("_wrap_Fl_Window_fullscreen_off__SWIG_0" Fl_Window_fullscreen_off) :void
  (self :pointer))

(cffi:defcfun ("_wrap_Fl_Window_fullscreen_off__SWIG_1" Fl_Window_fullscreen_off) :void
  (self :pointer)
  (X :int)
  (Y :int)
  (W :int)
  (H :int))

(cffi:defcfun ("_wrap_Fl_Window_fullscreen_active" Fl_Window_fullscreen_active) :unsigned-int
  (self :pointer))

(cffi:defcfun ("_wrap_Fl_Window_fullscreen_screens" Fl_Window_fullscreen_screens) :void
  (self :pointer)
  (top :int)
  (bottom :int)
  (left :int)
  (right :int))

(cffi:defcfun ("_wrap_Fl_Window_iconize" Fl_Window_iconize) :void
  (self :pointer))

(cffi:defcfun ("_wrap_Fl_Window_x_root" Fl_Window_x_root) :int
  (self :pointer))

(cffi:defcfun ("_wrap_Fl_Window_y_root" Fl_Window_y_root) :int
  (self :pointer))

(cffi:defcfun ("_wrap_Fl_Window_current" Fl_Window_current) :pointer)

(cffi:defcfun ("_wrap_Fl_Window_make_current" Fl_Window_make_current) :void
  (self :pointer))

(cffi:defcfun ("_wrap_Fl_Window_as_window" Fl_Window_as_window) :pointer
  (self :pointer))

(cffi:defcfun ("_wrap_Fl_Window_cursor__SWIG_0" Fl_Window_cursor) :void
  (self :pointer)
  (c Fl_Cursor)
  (arg2 :unsigned-int)
  (arg3 :unsigned-int))

(cffi:defcfun ("_wrap_Fl_Window_cursor__SWIG_1" Fl_Window_cursor) :void
  (self :pointer)
  (arg1 :pointer)
  (arg2 :int)
  (arg3 :int))

(cffi:defcfun ("_wrap_Fl_Window_default_cursor" Fl_Window_default_cursor) :void
  (self :pointer)
  (c Fl_Cursor)
  (arg2 :unsigned-int)
  (arg3 :unsigned-int))

(cffi:defcfun ("_wrap_Fl_Window_default_callback" Fl_Window_default_callback) :void
  (arg0 :pointer)
  (v :pointer))

(cffi:defcfun ("_wrap_Fl_Window_decorated_w" Fl_Window_decorated_w) :int
  (self :pointer))

(cffi:defcfun ("_wrap_Fl_Window_decorated_h" Fl_Window_decorated_h) :int
  (self :pointer))


